### ISSUE TITLE
ReadBin error when trying to import data

### ISSUE THREAD

**Issue by mcemerden** [meysubb/cfbscrapR-archived#55]
I'm using this code to get pbp data. 

```
cpbp <- data.frame()

for (j in 2012:2019){
  data <- data.frame()
  for(i in 1:15) {
    data2 <-
      cfb_pbp_data(year = j, season_type = "both", week = i, epa_wpa = FALSE) %>%
      mutate(week = i, year = j)
    data2 <- data.frame(data2)
    data <- bind_rows(data, data2)
  }
  cpbp <- bind_rows(cpbp, data)
}

```

However I'm getting this error:

Error in readBin(3L, raw(0), 32768L) : 
  transfer closed with 10396534 bytes remaining to read

I had no problem getting the data previously and have re-installed the package to no avail. Thanks
**R Version**
3.6.2

**Comment by spfleming** [comment]
Have you replicated the error with a smaller time frame? This is a large data pull; you may be running out of space. Try to pull fewer years at a time!

**Comment by mcemerden** [comment]
Yes I tried it with only a single season but got the same error. The i/js don't even go through a single iteration

**Comment by spfleming** [comment]
The week iteration is an unnecessary step, so this is probably a code error, not a package error. Can you try to run it with data2 being defined as:

`data2 <- cfb_pbp_data(year = j, season_type = "both", week = NULL, epa_wpa = FALSE)`

**Comment by mcemerden** [comment]
I realized some instability with my connection and trying my hotspot worked for now. I'll trying again when my connection is fixed and will close
